
# Built for libcxxabi in LLVM 12.0.0

# TODO: Use $(USE_MUSL_CLANG) to build with musl libc binaries.
#		Currently this is not working because musl-clang is not supporting C++.

LLVM_LIBCXXABI_SRC_PATH ?= ~/Downloads/llvm-project/libcxxabi
LLVM_LIBCXXABI_BUILD_DIR ?= $(BUILD_DIR)/llvm_libcxxabi_build

$(OBJ_BUILD)/llvm_libcxxabi.ll: $(OBJ_BUILD)/llvm_libcxx.ll $(BUILD_DIR)/musl_libc.ll build_makefile_app.sh
	@$(CREATE_DEST_DIR)
	@mkdir -p "$(LLVM_LIBCXXABI_BUILD_DIR)"

	cmake -B "$(LLVM_LIBCXXABI_BUILD_DIR)" -S "$(LLVM_LIBCXXABI_SRC_PATH)" \
		-DCMAKE_CROSSCOMPILING=True \
		-DCMAKE_C_COMPILER=wllvm \
		-DCMAKE_CXX_COMPILER=wllvm++ \
		-DCMAKE_C_FLAGS="$(CXXFLAGS_FOR_LIBCXX)" \
		-DCMAKE_CXX_FLAGS="$(CXXFLAGS_FOR_LIBCXX)" \
		-DLLVM_INCLUDE_TESTS=OFF \
		-DLIBCXXABI_ENABLE_SHARED=OFF \
		-DLIBCXXABI_USE_LLVM_UNWINDER=ON \
		-DLIBCXXABI_HAS_PTHREAD_API=ON \
		-DLIBCXXABI_BAREMETAL=ON \
		-DLIBCXXABI_LIBCXX_INCLUDES="$(LIBCXX_INCLUDE_DIR)" \
		-DCMAKE_SYSTEM_INCLUDE_PATH="$(MUSL_INCLUDE_DIR)" \
		-U LIBCXXABI_HAS_CXA_THREAD_ATEXIT_IMPL -D LIBCXXABI_HAS_CXA_THREAD_ATEXIT_IMPL=0
	
	PROJECT_PATH="$(LLVM_LIBCXXABI_BUILD_DIR)" \
	BINARY_FILE="$(LLVM_LIBCXXABI_BUILD_DIR)/lib/libc++abi.a" \
	OUTPUT_FILE=$@ \
	EXEC_CONFIGURE=false \
	EXEC_MAKE_INSTALL=false \
		./build_makefile_app.sh