// SPDX-FileCopyrightText: 2020 Gerion Entrup <entrup@sra.uni-hannover.de>
//
// SPDX-License-Identifier: GPL-3.0-or-later

/*
 * This file is used for automatic attribute creation for all syscall categories within the call graph.
 * ATTENTION: This file must kept in sync with the SyscallCategory enum in mix.py
 */

ARA_SYS_ACTION(undefined)
ARA_SYS_ACTION(every)
ARA_SYS_ACTION(create)
ARA_SYS_ACTION(comm)
